#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rt-tests
Version  : 1.3
Release  : 1
URL      : https://mirrors.edge.kernel.org/pub/linux/utils/rt-tests/rt-tests-1.3.tar.xz
Source0  : https://mirrors.edge.kernel.org/pub/linux/utils/rt-tests/rt-tests-1.3.tar.xz
Summary  : Programs used to test Priority Inheritance Mutexes
Group    : Development/Tools
License  : GPL-2.0
BuildRequires : numactl-dev

%description
The pi_tests package contains programs used to test the functionality of 
the priority inheritance attribute of POSIX mutexes on the Linux kernel

%prep
%setup -q -n rt-tests-1.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1528388140
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1528388140
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)
/usr/local/bin/cyclicdeadline
/usr/local/bin/cyclictest
/usr/local/bin/deadline_test
/usr/local/bin/hackbench
/usr/local/bin/pi_stress
/usr/local/bin/pip_stress
/usr/local/bin/pmqtest
/usr/local/bin/ptsematest
/usr/local/bin/queuelat
/usr/local/bin/rt-migrate-test
/usr/local/bin/sendme
/usr/local/bin/signaltest
/usr/local/bin/sigwaittest
/usr/local/bin/svsematest
/usr/local/share/man/man4/backfire.4.gz
/usr/local/share/man/man8/cyclictest.8.gz
/usr/local/share/man/man8/hackbench.8.gz
/usr/local/share/man/man8/pi_stress.8.gz
/usr/local/share/man/man8/pmqtest.8.gz
/usr/local/share/man/man8/ptsematest.8.gz
/usr/local/share/man/man8/rt-migrate-test.8.gz
/usr/local/share/man/man8/sendme.8.gz
/usr/local/share/man/man8/signaltest.8.gz
/usr/local/share/man/man8/sigwaittest.8.gz
/usr/local/share/man/man8/svsematest.8.gz
/usr/local/src/backfire/Makefile
/usr/local/src/backfire/backfire.c
